<%@ taglib prefix="s" uri="/struts-tags" %>
<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles" %>
 
<tiles:insertTemplate template="/pages/template.jsp" flush="true">

<tiles:putAttribute name="header">
    <title>CFE Wizard - Database Upload</title>
    <s:head />
</tiles:putAttribute>
<tiles:putAttribute name="content">

<script>
$( document ).ready(function() {
    
	// Use the filter values to hide non-applicable past results table rows
	function updatePastResults() {
	    phene = $("#cfeResultsPheneSelect").val().trim();
	    resultsType = $("#cfeResultsTypesSelect").val().trim();
	    // alert("Phene: " + phene + ", results type: " + resultsType);
	    
	    let table = $("#pastResultsTable");
	    let trs = $("tr", table);
	    for (let i = 1; i < trs.length; i++) {
	    	let tr = trs[i];
	    	let tds = $("td", tr);
	    	let rowResultsType = $(tds[2]).text().trim();
	    	let rowPhene = $(tds[4]).text().trim();
	    	
	    	if ((resultsType == "ALL" || resultsType == rowResultsType) && (phene == "ALL" || phene == rowPhene)) {
	            tr.style.display = ''; 
	    	}
	    	else {
	           tr.style.display = 'none';
	        }
	    
	    	// alert(rowResultsType + " " + rowPhene);
	    }
	    
	}
	
    $("#cfeResultsPheneSelect").on("change", function(event) {
        updatePastResults();
    });
    
    $("#cfeResultsTypesSelect").on("change", function(event) {
        updatePastResults();
    });
    
    $(".pastResultsRadio").on("click", function(event) {
    	//let checked = 
    	//alert($(this).attr("class"));
        if ($(this).hasClass("on")) {
            $(this).prop("checked", false);
            $(this).removeClass("on");
        }
        else {
        	$(".pastResultsRadio").removeClass("on");
            $(this).addClass("on");
        	$(this).prop("checked", true);
        }
        
        // $(this).toggleClass("on");
         
    	//if (checked) {
    	//	alert("Checked!");
    	//}
    	//else {
    	//	alert("Not checked.");
    	//}
    	//$(this).prop('checked', false);
    });
});

function submitForm() {
	document.getElementById("uploadButton").disabled = true;
	document.body.style.cursor='wait';
	document.uploadForm.submit();
}
</script>

<s:include value="/pages/batch/steps.jsp"/>

<s:include value="/pages/error_include.jsp"/>
        
<s:actionerror />  

<s:form id ="dataUploadForm" theme="simple" name="dataUploadForm"
        action="BatchDataUpload"
        method="post" enctype="multipart/form-data">

    <script>
    $( function() {
    	$("#dataUploadForm").on('submit', function(event) {
    	    $('input[type="submit"]').prop('disabled', true);
            $("body").css("cursor", "wait");
    	});
    });
    </script>
    
    <!-- <s:submit value="Upload" id="uploadButton" onclick="submitForm();" /> -->
    <p>
    <s:submit value="Upload" id="uploadButton" class="submit"/>
    </p>
    
    <hr/>        
    
    <s:hidden name="testingDbTempFileName" />     
    <s:token />
    
    <p>
    <span style="font-weight: bold;">Phenomic Database:</span>
    <s:file name="testingDb" label="Testing Database" />

    <hr/>
    
    <p>
    <span style="font-weight: bold;">Ending Step:</span>
    <s:select name="endingResultsType" list="endingResultsTypeList" value="@cfe.model.CfeResultsType@TESTING_SCORES"/>
    <i id="endHelpButton" style="margin-left: 1em;" class="fa fa-question-circle"></i>
    </p>
    
    <%-- END HELP DIALOG --%>
    <div id="endHelpDialog" title="Ending Step">
        <p>
        By default, the CFE Pipeline's ending step is the last step (Testing Scoring).
        You can specify an earlier ending step where the CFE Pipeline should end.
        </p>
        <p>
        This can be useful if you need to modify the results generated by the CFE
        Wizard at an intermediate step before proceeding. 
        </p>
    </div>
    <script>
    $( function() {
        $("#endHelpDialog").dialog({dialogClass: 'helpDialog', width: 500}).dialog('close');
        $("#endHelpButton").on("click", function() {
        	$("#endHelpDialog").dialog('open');	
        });
    });
    </script>
    
    <%--
    <hr/>
    
    <p>
    <span style="font-weight: bold;">Skip Validation Steps:</span>
    <s:checkbox name="skipValidationSteps"/> (WORK IN PROGRESS)
    </p>
    --%>
    
    <hr/>
    
    
    <p style="font-weight: bold;">Other Starting Point (Optional)
    <i id="startHelpButton" style="margin-left: 1em;" class="fa fa-question-circle"></i>
    </p>
    
    <%-- START HELP DIALOG --%>
    <div id="startHelpDialog" title="Other Starting Point">
        <p>
        By default, the CFE Pipeline starts calculating at the first step (Discovery Cohort Creation).
        However, you can optionally specify a later starting point by specifying a manually
        created spreadsheet that has results for a later step, or results of a step
        that was previously saved by the CFE Wizard.
        </p>
    </div>
    <script>
    $( function() {
        $("#startHelpDialog").dialog({dialogClass: 'helpDialog', width: 500}).dialog('close');
        $("#startHelpButton").on("click", function() {
        	$("#startHelpDialog").dialog('open');	
        });
    });
    </script>

    <div style="margin-left: 3em;">
    
        <fieldset class="dataInput">
            <p style="font-weight: bold;">
            <s:radio class="pastResultsRadio" name="startingCfeResultsId" list="#{@cfe.action.BatchAction@MANUAL_RESULTS_START: 'Manually created spreadsheet:'}"/>
            <i id="manuallyCreatedHelpButton" style="margin-left: 1em;" class="fa fa-question-circle"></i>    
            </p>
            
            <%-- MANUALLY CREATED HELP DIALOG --%>
            <div id="manuallyCreatedHelpDialog" title="Manually Created Spreadsheet">
                <s:include value="/pages/help/manuallyCreatedSpreadsheet.jsp"/>
            </div>
            <script>
            $( function() {
                $("#manuallyCreatedHelpDialog").dialog({dialogClass: 'helpDialog', width: 720}).dialog('close');
                $("#manuallyCreatedHelpButton").on("click", function() {
        	        $("#manuallyCreatedHelpDialog").dialog('open');	
                });
            });
            </script>
            
            
            <div style="margin-left: 3em;">
                <div style="margin-bottom: 7px;">
                    <%--
                    Type: <s:select name="manualResultsType" list="manualResultsTypeList" value="@cfe.model.CfeResultsType@DISCOVERY_COHORT"/>
                    &nbsp;
                    --%> 
                    Spreadsheet: <s:file name="manualResultsSpreadsheet" label="Spreadsheet"/>
                </div>
                
                <%--
                <div style="margin-bottom: 7px;">
                <s:radio name="manualPheneInfoSource" list="#{'spreadsheet': 'Get discovery phene info from spreadsheet'}" checked="true"/>
                --%>
                <%-- <a href="#" target="_blank" class="help" onclick="window.open('home.jsp');">?</a> --%>

                <%-- </div> --%>
                
                <%--
                <div style="margin-bottom: 5px;">
                <s:radio name="manualPheneInfoSource" list="#{'input': 'Enter discovery phene info:'}"/>
                </div>
                
                <div style="margin-left: 3em;">

                    <div style="margin-bottom: 5px;">
                    Discovery Phene: <s:textfield name="discoveryPheneInfo"/> format: <i>table-name.phene-name</i> (e.g., "PANSS.P1 Delusions (1-7)")
                    </div>
                    <div>
                    Discovery Phene Low Cutoff (phene &ge;): <s:textfield name="discoveryPheneLowCutoff" style="text-align: right;" size="4"/>
                    &nbsp; Discovery Phene High Cutoff (phene &le;): <s:textfield name="discoveryPheneHighCutoff" style="text-align: right;" size="4"/>
                    </div>
                </div>
                --%>
            </div>
        </fieldset>
    
        <fieldset class="dataInput" style="margin-top: 17px;">
            <p style="font-weight: bold;">
            Past calculated or uploaded result:
            </p>
            
            <div style="margin-bottom: 22px; margin-left: 3em; border: 1px solid #000000; border-radius: 7px; padding: 7px; background-color: #F5F5FF;">
                <span style="font-weight: bold; margin-left: 1em;">Phene:</span> 
                <s:select id="cfeResultsPheneSelect" list="resultsPhenes" name="resultsPhene" value="resultsPhene">
                </s:select>
                
                <span style="font-weight: bold; margin-left: 1em;">Type:</span> 
                <s:select id="cfeResultsTypesSelect" list="cfeResultsTypes" name="cfeResultsType" value="cfeResultsType">
                </s:select>
            </div>

            <table class="dataTable" id="pastResultsTable" style="margin-left: 3em;">
                <tr> 
                    <th>ID</th>
                    <th>Results</th>
                    <th>Results Type</th>
                    <th>Time Generated</th>
                    <th>Phene</th>
                    <th>Phene Low Cutoff</th>
                    <th>Phene High Cutoff</th>
                </tr>

                <s:if test="startingResultsList != null">
                    <s:iterator value="startingResultsList" var="result">
                        <tr>
                            <td>
                                <s:radio class="pastResultsRadio" name="startingCfeResultsId" list="{cfeResultsId}"/>
                            </td>
                            <td>
                                <s:a action="CfeResultsXlsxDisplay" title="Discovery Results">
                                    <s:param name="cfeResultsId" value="cfeResultsId" />
                                    results.xlsx
                                </s:a>
                            </td>
                            <td> <s:property value="resultsType"/>
                            <td> <s:date name="generatedTime" format="MM/dd/yyyy hh:mm"/> </td>
                            <td> <s:property value="phene"/> </td>
                            <td style="text-align: right;"> <s:property value="lowCutoff"/> </td>
                            <td style="text-align: right;"> <s:property value="highCutoff"/> </td>
                        </tr>
                    </s:iterator>
                </s:if>
            </table>
        </fieldset>
        
    </div>


</s:form>

<s:iterator value="validationMsgs" status="vstat">
    <s:property value="validationMsgs[%{#vstat.index}]" />
</s:iterator>

</tiles:putAttribute>
</tiles:insertTemplate>
