<%@ taglib prefix="s" uri="/struts-tags" %>
<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles" %>

<p>
The format of manually created or modified spreadsheets
should be the same as the format of the spreadsheets
generated by the CFE Wizard.
The CFE Wizard will infer the "results type" (e.g., "discovery cohort", "discovery scores", "prioritization scores") of an uploaded
spreadsheet based on the names of the sheets that it contains.
</p>
 
<p>
For the CFE Wizard to get the discovery phene information from an uploaded spreadsheet,
it needs to contain a sheet named 
<strong>"<s:property value="@cfe.model.CfeResultsSheets@DISCOVERY_COHORT_INFO"/>"</strong>
that contains the following information (example phene name and cutoffs shown):
</p>

 <table class="dataTable">
     <tr>
         <td style="font-weight: bold;">attribute</td>	<td style="font-weight: bold;">value</td>
     </tr>
     <tr>
         <td>Phene</td> <td>PANSS.P1 Delusions (1-7) </td>
     </tr> 
     <tr>
         <td>Low Cutoff</td>	<td style="text-align: right;">1</td>
     </tr>
     <tr>
         <td>High Cutoff</td> <td style="text-align: right;">4</td>
     </tr>
 </table>
 <p>
 Note: the phene name needs to contain the phene's database table name ("PANSS" in the example above)
 and phene name separated by a "."
 </p>
