package cfe.calc;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.logging.Logger;

/**
 * Calculation utility class with calculation methods that are not specific to one phase
 * of the CFE pipeline.
 * 
 * @author Jim Mullen
 *
 */
public class CalcUtil {
    
    private static final Logger log = Logger.getLogger(CalcUtil.class.getName());
    
    /** 
     * Executes the specified command and returns the output from the command.
     *
     * @param command the command to execute
     * @return the output generated by the command
     * @throws Exception
     */
    public static String runCommand(String[] command) throws Exception {
        StringBuilder output = new StringBuilder();
        
        log.info("run command: " + String.join(" ", command));
        
        // This allows debugging:
        ProcessBuilder processBuilder = new ProcessBuilder(command);
        processBuilder.redirectErrorStream(true); // redirect standard error to standard output
        
        Process process = processBuilder.start();

        BufferedReader reader = new BufferedReader(
        new InputStreamReader(process.getInputStream()));

        String line;
        while ((line = reader.readLine()) != null) {
            output.append(line + "\n");
        }

        log.info("Waiting for process...");
        int status = process.waitFor();
        if (status != 0) {
            //throw new Exception("Command \"" + command + "\" exited with code " + status);
        }
        
        reader.close();
        return output.toString();
    }
}
