package cfe.model;

/**
 * Class for representing the information for the running of a script.
 * 
 * @author Jim Mullen
 *
 */
public class ScriptRunInfo {
    private String command;  // The command used to run the script
    private String output;   // The output generated by the script
    
    public String getCommand() {
        return command;
    }
    
    public void setCommand(String command) {
        this.command = command;
    }
    
    public String getOutput() {
        return output;
    }
    
    public void setOutput(String output) {
        this.output = output;
    }

}
