
CREATE TABLE `disorder` (
  `disorderId` int(11) NOT NULL AUTO_INCREMENT,
  `domain` varchar(255) DEFAULT NULL,
  `relevantDisorder` varchar(255) DEFAULT NULL,
  `subdomain` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`disorderId`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `genelist` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `hubraingene` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `accessionNumber` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `authorId` varchar(255) DEFAULT NULL,
  `brainRegion` varchar(255) DEFAULT NULL,
  `comments` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `females` varchar(255) DEFAULT NULL,
  `flaggedStudies` varchar(255) DEFAULT NULL,
  `geneName` varchar(255) DEFAULT NULL,
  `males` varchar(255) DEFAULT NULL,
  `numberOfSubjects` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sampleSource` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `hubrainmet` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `authorId` varchar(255) DEFAULT NULL,
  `brainTissue_CellLine` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `females` varchar(255) DEFAULT NULL,
  `males` varchar(255) DEFAULT NULL,
  `moleculeId` varchar(255) DEFAULT NULL,
  `moleculeName` varchar(255) DEFAULT NULL,
  `moleculeType` varchar(255) DEFAULT NULL,
  `numberOfSubjects` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sampleSource` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `hubrainprot` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `authorId` varchar(255) DEFAULT NULL,
  `brainTissue_CellLine` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `females` varchar(255) DEFAULT NULL,
  `males` varchar(255) DEFAULT NULL,
  `moleculeType` varchar(255) DEFAULT NULL,
  `numberOfSubjects` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `proteinId` varchar(255) DEFAULT NULL,
  `proteinName` varchar(255) DEFAULT NULL,
  `sampleSource` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `hugeneassoc` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `PValue` varchar(255) DEFAULT NULL,
  `SNP` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `author_Date` varchar(255) DEFAULT NULL,
  `chromosome` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `females` varchar(255) DEFAULT NULL,
  `geneName` varchar(255) DEFAULT NULL,
  `males` varchar(255) DEFAULT NULL,
  `numNomSigSNPs` varchar(255) DEFAULT NULL,
  `numberOfSubjects` varchar(255) DEFAULT NULL,
  `originOfSample` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `hugenecnv` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CNV` varchar(255) DEFAULT NULL,
  `PValue` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `author_Date` varchar(255) DEFAULT NULL,
  `chromosome` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `females` varchar(255) DEFAULT NULL,
  `geneName` varchar(255) DEFAULT NULL,
  `males` varchar(255) DEFAULT NULL,
  `numberOfSubjects` varchar(255) DEFAULT NULL,
  `originOfSample` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `hugenelinkage` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `LODScore` varchar(255) DEFAULT NULL,
  `NPLScore` varchar(255) DEFAULT NULL,
  `PValue` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `author_Date` varchar(255) DEFAULT NULL,
  `chromosomalLocus` varchar(255) DEFAULT NULL,
  `chromosome` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `females` varchar(255) DEFAULT NULL,
  `locationFromPaper` varchar(255) DEFAULT NULL,
  `males` varchar(255) DEFAULT NULL,
  `manuscriptMarker` varchar(255) DEFAULT NULL,
  `mapOMapFemaleMapPos` varchar(255) DEFAULT NULL,
  `mapOMapMaleMapPos` varchar(255) DEFAULT NULL,
  `mapOMapMarkerName` varchar(255) DEFAULT NULL,
  `mapOMapSexAverage` varchar(255) DEFAULT NULL,
  `numberOfSubjects` varchar(255) DEFAULT NULL,
  `originOfSample` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `hupergene` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `accessionNumber` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `authorId` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `females` varchar(255) DEFAULT NULL,
  `geneName` varchar(255) DEFAULT NULL,
  `males` varchar(255) DEFAULT NULL,
  `numberOfSubjects` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `typePeripheralTissue` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `hupermet` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `authorId` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `females` varchar(255) DEFAULT NULL,
  `males` varchar(255) DEFAULT NULL,
  `moleculeId` varchar(255) DEFAULT NULL,
  `moleculeName` varchar(255) DEFAULT NULL,
  `moleculeType` varchar(255) DEFAULT NULL,
  `numberOfSubjects` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `typePeripheralTissue` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `huperprot` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `authorId` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `females` varchar(255) DEFAULT NULL,
  `males` varchar(255) DEFAULT NULL,
  `moleculeType` varchar(255) DEFAULT NULL,
  `numberOfSubjects` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `proteinId` varchar(255) DEFAULT NULL,
  `proteinName` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `typePeripheralTissue` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `nhbraingene` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `animalType` varchar(255) DEFAULT NULL,
  `author_Date` varchar(255) DEFAULT NULL,
  `brainTissue_CellLine` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `geneName` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `studyType` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `treatment` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `nhbrainmet` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `animalType` varchar(255) DEFAULT NULL,
  `author_Date` varchar(255) DEFAULT NULL,
  `brainTissue_CellLine` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `moleculeId` varchar(255) DEFAULT NULL,
  `moleculeName` varchar(255) DEFAULT NULL,
  `moleculeType` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `studyType` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `treatment` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `nhbrainprot` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `animalType` varchar(255) DEFAULT NULL,
  `authorId` varchar(255) DEFAULT NULL,
  `brainTissue_CellLine` varchar(255) DEFAULT NULL,
  `dateAdded` datetime DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `moleculeType` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `proteinId` varchar(255) DEFAULT NULL,
  `proteinName` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `studyType` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `treatment` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `nhgeneassoc` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `PValue` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `animalType` varchar(255) DEFAULT NULL,
  `author_Date` varchar(255) DEFAULT NULL,
  `chromosome` varchar(255) DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `geneName` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `studyType` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `nhgenecnv` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CNV` varchar(255) DEFAULT NULL,
  `PValue` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `animalType` varchar(255) DEFAULT NULL,
  `author_Date` varchar(255) DEFAULT NULL,
  `chromosome` varchar(255) DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `geneName` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `studyType` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `nhgenelinkage` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `LODScore` varchar(255) DEFAULT NULL,
  `PValue` varchar(255) DEFAULT NULL,
  `QTL` varchar(255) DEFAULT NULL,
  `QTLLocation` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `animalType` varchar(255) DEFAULT NULL,
  `author_Date` varchar(255) DEFAULT NULL,
  `chromosome` varchar(255) DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `studyType` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `nhpergene` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `animalType` varchar(255) DEFAULT NULL,
  `author_Date` varchar(255) DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `geneName` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `studyType` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `treatment` varchar(255) DEFAULT NULL,
  `typePeripheralTissue` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `nhpermet` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `animalType` varchar(255) DEFAULT NULL,
  `author_Date` varchar(255) DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `moleculeId` varchar(255) DEFAULT NULL,
  `moleculeName` varchar(255) DEFAULT NULL,
  `moleculeType` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `studyType` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `treatment` varchar(255) DEFAULT NULL,
  `typePeripheralTissue` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `nhperprot` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `CChange` varchar(255) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `additionalInfo` varchar(255) DEFAULT NULL,
  `animalType` varchar(255) DEFAULT NULL,
  `author_Date` varchar(255) DEFAULT NULL,
  `descriptiveName` varchar(255) DEFAULT NULL,
  `moleculeType` varchar(255) DEFAULT NULL,
  `paperSymbol` varchar(255) DEFAULT NULL,
  `proteinId` varchar(255) DEFAULT NULL,
  `proteinName` varchar(255) DEFAULT NULL,
  `sourceInfo` varchar(255) DEFAULT NULL,
  `studyType` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `treatment` varchar(255) DEFAULT NULL,
  `typePeripheralTissue` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `scoringdata` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `directionChange` varchar(255) DEFAULT NULL,
  `genecardSymbol` varchar(255) DEFAULT NULL,
  `psychiatricDomain` varchar(50) DEFAULT NULL,
  `pubMedID` double NOT NULL,
  `relevantDisorder` varchar(50) DEFAULT NULL,
  `subDomain` varchar(50) DEFAULT NULL,
  `tissue` varchar(255) DEFAULT NULL,
  `huBrainScore` double NOT NULL,
  `huGeneAssocScore` double NOT NULL,
  `huGeneCnvScore` double NOT NULL,
  `huGeneLinkageScore` double NOT NULL,
  `huPerScore` double NOT NULL,
  `nhBrainScore` double NOT NULL,
  `nhGeneAssocScore` double NOT NULL,
  `nhGeneCnvScore` double NOT NULL,
  `nhGeneLinkageScore` double NOT NULL,
  `nhPerScore` double NOT NULL,
  `srcTableName` varchar(30) DEFAULT NULL,
  `tableName` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

